"""add user, user_session, frame models

Revision ID: b51bab782a92
Revises: 
Create Date: 2023-07-05 23:26:25.633373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51bab782a92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False, comment='user name'),
    sa.Column('ip', sa.String(length=39), nullable=False, comment='ip address'),
    sa.Column('machine_name', sa.String(length=40), nullable=False, comment='machine name'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('ip', name=op.f('uq_users_ip')),
    sa.UniqueConstraint('machine_name', name=op.f('uq_users_machine_name')),
    sa.UniqueConstraint('name', name=op.f('uq_users_name')),
    schema='public'
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='session id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='user id'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], name=op.f('fk_user_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('session_id', name=op.f('uq_user_sessions_session_id')),
    schema='public'
    )
    op.create_table('frames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('frame_create_time', sa.TIME(), nullable=False, comment='frame create time'),
    sa.Column('user_session_id', sa.Integer(), nullable=False, comment='user session id'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_session_id'], ['public.user_sessions.id'], name=op.f('fk_frames_user_session_id_user_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frames')),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frames', schema='public')
    op.drop_table('user_sessions', schema='public')
    op.drop_table('users', schema='public')
    # ### end Alembic commands ###
