name: Python application test

on: [push]
env:
  POSTGRES_USER: postgres
  POSTGRES_DB: sample
  POSTGRES_PASSWORD: postgres
  POSTGRES_SERVER: localhost
  POSTGRES_PORT: 5432
  PYTHONPATH: ${{ github.workspace }}
jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test with pytest
        run: |
          pytest -v
  docs-deploy:
    needs: test-python
    uses: ./.github/workflows/docs.yml
